-- EJERCICIO 1

SELECT DISTINCT PAPELERIAS.NOMP
FROM PAPELERIAS
JOIN ELP ON PAPELERIAS.P# = ELP.P#
JOIN EDITORIALES ON ELP.E# = EDITORIALES.E#
WHERE EDITORIALES.CIUDAD = 'Madrid';

SELECT DISTINCT ELP.P#
FROM ELP
JOIN LIBROS ON ELP.L# = LIBROS.L#
WHERE LIBROS.AÑO >= 1978
AND ELP.P# IN ('P1', 'P3');

SELECT DISTINCT P#
FROM ELP
WHERE E# = 'E1'
AND P# NOT IN (
  SELECT P#
  FROM ELP
  WHERE E# != 'E1'
);

SELECT DISTINCT LIBROS.TITULO
FROM LIBROS
JOIN ELP ON LIBROS.L# = ELP.L#
JOIN PAPELERIAS ON ELP.P# = PAPELERIAS.P#
WHERE ELP.CANTIDAD > 100
AND PAPELERIAS.CIUDAD != 'Madrid';

-- EJERCICIO 2

SELECT DISTINCT U#
FROM USOS
WHERE P# IN (
  SELECT P#
  FROM PROGRAMAS
  WHERE DISTRIBUIDOR = 'D1'
)
GROUP BY U#
HAVING COUNT(DISTINCT P#) = (
  SELECT COUNT(DISTINCT P#)
  FROM PROGRAMAS
  WHERE DISTRIBUIDOR = 'D1'
);

SELECT DISTINCT P#
FROM PROGRAMAS
WHERE P# NOT IN (
  SELECT P#
  FROM USOS
  JOIN USUARIOS ON USOS.U# = USUARIOS.U#
  WHERE USUARIOS.EDAD < 18
);

SELECT DISTINCT ORDENADORES.MODELO
FROM ORDENADORES
JOIN USOS ON ORDENADORES.O# = USOS.O#
JOIN USUARIOS ON USOS.U# = USUARIOS.U#
WHERE USUARIOS.EDAD > 30
  AND USOS.TIEMPO > 3;
